### ISSUE TITLE
正しいTOKENを渡してるはずなのに無効なトークンだとしてエラーが発生する

### ISSUE THREAD

**Issue by Meru92** [Memoria-Project/MemoriaChan#3]
### 問題点
- MemoriaChanは [dotenv](https://www.npmjs.com/package/dotenv) というnpmモジュールを使って環境変数(.env)に機密情報(TOKEN)を渡している
- 2021/04/29 gitのロールバックでBotが起動しなくなった。

![image](https://user-images.githubusercontent.com/82575685/116442557-95ae1100-a88d-11eb-95ff-51ed2ad076ab.png)

### エラー文
```
[success] command: aboutを読み込みました
[success] command: helpを読み込みました
[success] command: pingを読み込みました
[success] command: userinfoを読み込みました
(node:19828) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\piki0\Desktop\Minecraft_Server\Bedrock_Edition\Memoria\memoriachan\node_modules\discor
d.js\src\client\Client.js:206:52)
    at Object.<anonymous> (C:\Users\piki0\Desktop\Minecraft_Server\Bedrock_Edition\Memoria\memoriachan\index.js:56:8
)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see h
ttps://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.
```
- [コマンド処理のjsファイル](https://github.com/Memoria-Project/MemoriaChan/tree/master/commands/category)は読み込んだ。
- 無効なトークンと出る。リセットしてもうまく行かない

**Comment by Meru92** [comment]
```js
const { Client, Collection, Intents } = require("discord.js");
const {config} = require("dotenv");

const options = {
    ws: {
        intents: Intents.ALL,
    },
};

const client = new Client(options);
/** 特権インテンスの有効化 */
const prefix = "m:"
/** コマンドのPrefix */
/** https://guide.discordjs-japan.org/creating-your-bot/adding-more-commands.html */


config({
    path: __dirname + "/.env"
});

client.commands = new Collection();
client.aliases = new Collection();

["command"].forEach(handler => {
    require(`./handlers/${handler}`)(client)
});

client.on("ready", () => {
    console.log(`全てのコマンドを読み込みました。 Login：${client.user.tag} Done.`);
    client.user.setActivity('Type m:help｜Ver:' + '1.0.2')
});

client.on("message", message => {
    if (message.author.bot) return;
    if (!message.guild) return;
    if (!message.content.startsWith(prefix)) return;

    const args = message.content.slice(prefix.length).trim().split(/ +/g);
    const cmd = args.shift().toLowerCase();

    if (cmd.length === 0) return;

    let command = client.commands.get(cmd);
    if (!command) command = client.commands.get(client.aliases.get(cmd));


    if (!command) return;

    if (command.enabled) {
        command.run(client, message, args);
        console.log("[CommandUsageLog]" + message.author.username + "が" + command.name + "を使用しました");
    }
});

client.login(process.env.TOKEN);
```
```env
TOKEN:
```

**Comment by Meru92** [comment]
`.env` で値を `:` で繋いでた
